version: '3'

services:
  dns:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    #  - ./conf/named:/etc/default/named
      - ./conf/named.conf.options:/etc/bind/named.conf.options
    #  - ./conf/named.conf.default-zones:/etc/bind/named.conf.default-zones
    #  - ./conf/db.redirect:/etc/bind/db.redirect
      - $QUERY_LOG:/var/log/named
    ports:
      - 53:53
      - 53:53/udp
